{
 "title": "Camunda",
 "description": "Camunda metrics dashboard",
 "tags": [ "camunda" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Process Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Process Instances",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_process_instances"
      }
     ]
    },
    {
     "title": "Completed Process Instances",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_completed_process_instances"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Definitions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Process Definitions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_process_definitions"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Deployments",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_deployments" }
     ]
    }
   ]
  },
  {
   "title": "Incidents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Incidents",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_active_incidents" }
     ]
    }
   ]
  },
  {
   "title": "Timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executable Timer Jobs",
     "type": "graph",
     "description": "Timers that are ready to be executed (past due date)",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_executable_timer_jobs" }
     ]
    },
    {
     "title": "Timer Jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_timer_jobs" }
     ]
    }
   ]
  },
  {
   "title": "User Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active User Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_active_user_tasks" }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executable Jobs",
     "type": "graph",
     "description": "Jobs ready to be executed (past due date)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_executable_jobs" }
     ]
    },
    {
     "title": "Message Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_message_jobs" }
     ]
    }
   ]
  },
  {
   "title": "External Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active External Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_active_external_tasks" }
     ]
    },
    {
     "title": "Active Locked External Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_locked_external_tasks"
      }
     ]
    },
    {
     "title": "Active Not Locked External Tasks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_not_locked_external_tasks"
      }
     ]
    }
   ]
  },
  {
   "title": "Event Subscriptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Message Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_message_event_subscriptions"
      }
     ]
    },
    {
     "title": "Active Signal Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_signal_event_subscriptions"
      }
     ]
    },
    {
     "title": "Active Compensate Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_compensate_event_subscriptions"
      }
     ]
    },
    {
     "title": "Active Conditional Event Subscriptions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "camunda_active_conditional_event_subscriptions"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_user_count" }
     ]
    }
   ]
  },
  {
   "title": "Tenants",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tenant Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "camunda_tenant_count" }
     ]
    }
   ]
  }
 ]
}